version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: 
            name: "Create CloudFormation Stack"
            command: |
              aws cloudformation deploy \
              --template-file infrastructure-template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["b2:a8:82:53:14:dd:be:09:df:50:b2:34:84:cf:a9:91"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i [inventory-file] [playbook-file]

# Sequential workflow
workflows:
  # Name the workflow
  Infrastructure-Workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure  
      